### PR TITLE
Fixed calculator state after rotation

### LINKED ISSUE #204: Calculator loses state after rotation

### PR DESCRIPTION
**Pull request by i906**
Fixes #204. Though after rotating screen, numbers without decimals will add `.0` to the back, e.g. `2 x 2.5` will be `2.0 x 2.5`.

### CODE REVIEW

File: financius/src/main/java/com/code44/finance/ui/CalculatorFragment.java [hunk 1]
```diff
@@ -21,6 +21,7 @@
 public class CalculatorFragment extends BaseFragment implements View.OnClickListener, View.OnLongClickListener {
     private static final String ARG_VALUE = "ARG_VALUE";
     private static final String ARG_RAW_VALUE = "ARG_RAW_VALUE";
+    private static final String ARG_EXPRESSION = "ARG_EXPRESSION";
```
Comment (mvarnagiris) [inline financius/src/main/java/com/code44/finance/ui/CalculatorFragment.java]: Rename this ti STATE_EXPRESSION as this is not an argument but state

**Comment by mvarnagiris** [comment]
Nice job
